openapi: 3.0.0
info:
  title: JustMehr API
  description: API specification for JustMehr backend services.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/ABC52/SubscriptionAPI/1.0.0
  description: JustMehr backend API
security:
- accessCode:
  - read
  - write
paths:
  /courses:
    get:
      tags:
      - courses
      summary: List all courses available
      description: Provides list of all courses for software and school education
        currently available
      operationId: getCourses
      parameters:
      - name: page
        in: query
        description: page number
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: size
        in: query
        description: How many items to return at one time
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          headers:
            x-next:
              description: A link to the next page of responses
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courses'
components:
  schemas:
    Course:
      required:
      - courseDuration
      - courseType
      - id
      - name
      - startDate
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        courseDuration:
          type: integer
          format: int64
        startDate:
          type: string
          format: date
        courseType:
          type: string
    Courses:
      type: array
      items:
        $ref: '#/components/schemas/Course'
    Error:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    accessCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://example.com/oauth/auth
          tokenUrl: http://example.com/oauth/token
          scopes:
            write: allows modifying resources
            read: allows reading resources
